### common
server:
  port: 8100
  tomcat:
    threads:
      max: 50
management:
  endpoints:
    web:
      # for actuator
      base-path: /
      exposure:
        include:
        - "health"
        - "configprops"
        - "info"
  endpoint:
    health:
      show-details: "ALWAYS"

### for spring
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;
    username: sa
    password: 
#    username: root
#    password: root
#    url: jdbc:mysql://127.0.0.1:3302/user_info
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: ["classpath:/db/migration"]
