### common
server:
  port: 8100
  tomcat:
    threads:
      max: 50
management:
  endpoints:
    web:
      # for actuator
      base-path: /
      exposure:
        include:
        - "health"
        - "configprops"
        - "info"
  endpoint:
    health:
      show-details: "ALWAYS"

### for spring
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: ["classpath:/db/migration"]
